trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        yarn install
        yarn run build
      displayName: 'npm install and build'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'fcSharedInbox'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy the Fc Shared Inbox to backend6'
  dependsOn: Build
  jobs:
  - deployment: 'DeployToBackend6'
    displayName: 'Deploy the Fc Shared Inbox to the BackendGroup environment'
    variables:
      Parameters.IISDeploymentType: 'iISWebsite'
      Parameters.ActionIISWebsite: 'CreateOrUpdateWebsite'
      Parameters.WebsiteName: 'fcSharedInbox'
      Parameters.Package: '$(Pipeline.Workspace)\fcSharedInbox\*.zip'
      Parameters.RemoveAdditionalFilesFlag: true
      Parameters.TakeAppOfflineFlag: true
      #Parameters.XmlTransformation: true
      #Parameters.XmlVariableSubstitution: true
    environment:
      name: BackendGroup
      resourceType: VirtualMachine
      tags: fcSharedInbox
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: fcSharedInbox
            
          